# Generated by Django 3.1.7 on 2021-04-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_document_documentfieldvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfieldvalue',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentfieldvalue',
            name='field',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentFieldValue',
        ),
    ]
