# Generated by Django 3.1.7 on 2021-03-28 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('element', models.CharField(blank=True, choices=[('input', 'Input')], default='input', max_length=20, null=True, verbose_name='Element')),
                ('input_type', models.CharField(blank=True, choices=[('text', 'Text'), ('url', 'Url'), ('email', 'Email')], default='text', max_length=20, null=True, verbose_name='Type')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.table')),
            ],
        ),
    ]
