# Generated by Django 3.1.7 on 2021-03-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='help_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Help text'),
        ),
        migrations.AddField(
            model_name='field',
            name='label',
            field=models.CharField(default='', max_length=100, verbose_name='Label'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='field',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Required'),
        ),
        migrations.AddField(
            model_name='field',
            name='unique',
            field=models.BooleanField(default=False, verbose_name='Unique'),
        ),
    ]
