# Generated by Django 3.1.7 on 2021-04-03 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20210403_0700'),
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='table.table'),
        ),
    ]
