# Generated by Django 3.1.7 on 2021-03-30 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
        ('fields', '0002_auto_20210328_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='table_field_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_field_related_related', to='fields.field'),
        ),
        migrations.AddField(
            model_name='field',
            name='table_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_related', to='table.table'),
        ),
        migrations.AddField(
            model_name='field',
            name='table_relation_type',
            field=models.CharField(blank=True, choices=[('foreign_key', 'Foreign key'), ('many_to_many', 'Many to many')], default='foreign_key', max_length=20, null=True, verbose_name='Table relation type'),
        ),
        migrations.AlterField(
            model_name='field',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='table.table'),
        ),
    ]
