# Generated by Django 3.1.7 on 2021-03-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_auto_20210330_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='element',
            field=models.CharField(blank=True, choices=[('input', 'Input'), ('foreign_key', 'Relation field (1 - 1)'), ('many_to_many', 'Relation field (1 - N)')], default='input', max_length=20, null=True, verbose_name='Element'),
        ),
    ]
