# Generated by Django 3.1.7 on 2021-03-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0005_remove_field_table_field_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='help_text',
        ),
        migrations.RemoveField(
            model_name='field',
            name='label',
        ),
        migrations.RemoveField(
            model_name='field',
            name='order',
        ),
    ]
